Repository CloudburstMC/Nukkit, pull requests merged in 2018-12, with the labels that each got.

#495 Fix GlowStone populator
  src/main/java/cn/nukkit/level/generator/populator/impl/PopulatorGlowStone.java
Labels: [Priority] Low, [Status] Waiting for Response, [Type] Enhancement

#499 Bedrock 1.8
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/block/BlockTripWireHook.java
  src/main/java/cn/nukkit/entity/item/EntityFirework.java
  src/main/java/cn/nukkit/entity/weather/EntityLightning.java
  src/main/java/cn/nukkit/inventory/transaction/CraftingTransaction.java
  src/main/java/cn/nukkit/item/ItemTrident.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/level/format/LevelProviderManager.java
  src/main/java/cn/nukkit/nbt/tag/CompoundTag.java
  src/main/java/cn/nukkit/nbt/tag/ListTag.java
  src/main/java/cn/nukkit/network/Network.java
  src/main/java/cn/nukkit/network/protocol/AddEntityPacket.java
  src/main/java/cn/nukkit/network/protocol/AvailableEntityIdentifiersPacket.java
  src/main/java/cn/nukkit/network/protocol/BiomeDefinitionListPacket.java
  src/main/java/cn/nukkit/network/protocol/LevelSoundEventPacket.java
  src/main/java/cn/nukkit/network/protocol/LevelSoundEventPacketV1.java
  src/main/java/cn/nukkit/network/protocol/NetworkChunkPublisherUpdatePacket.java
  src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
  src/main/java/cn/nukkit/network/protocol/ResourcePackStackPacket.java
  src/main/java/cn/nukkit/network/protocol/SpawnParticleEffectPacket.java
  src/main/java/cn/nukkit/network/protocol/StartGamePacket.java
  src/main/java/cn/nukkit/network/protocol/UpdateTradePacket.java
  src/main/java/cn/nukkit/network/protocol/types/NetworkInventoryAction.java
  src/main/resources/entity_identifiers.dat
  src/main/resources/runtimeid_table.json
Labels: [Priority] Urgent, [Status] In Progress..., [Type] Feature

#354 Enable eating sounds and particles
  src/main/java/cn/nukkit/Player.java
Labels: [Priority] Low, [Status] Needs Testing, [Type] Feature
