Repository CloudburstMC/Nukkit, pull requests merged in 2018-08, with the labels that each got.

#214 Create nether world if it doesn't exist
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/level/EnumLevel.java
Labels: [Priority] Low, [Status] Needs Testing, [Type] Enhancement

#335 Add trident and turtle shell
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/entity/projectile/EntityThrownTrident.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemArmor.java
  src/main/java/cn/nukkit/item/ItemID.java
  src/main/java/cn/nukkit/item/ItemTool.java
  src/main/java/cn/nukkit/item/ItemTrident.java
  src/main/java/cn/nukkit/item/ItemTurtleShell.java
  src/main/resources/creativeitems.json
Labels: [Priority] Low, [Status] Merged, [Type] Enhancement

#357 Update to 1.6 (282)
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/block/GlobalBlockPalette.java
  src/main/java/cn/nukkit/command/data/CommandParamType.java
  src/main/java/cn/nukkit/entity/item/EntityFallingBlock.java
  src/main/java/cn/nukkit/item/ItemPotionLingering.java
  src/main/java/cn/nukkit/level/GlobalBlockPalette.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/level/particle/DestroyBlockParticle.java
  src/main/java/cn/nukkit/level/particle/PunchBlockParticle.java
  src/main/java/cn/nukkit/level/particle/TerrainParticle.java
  src/main/java/cn/nukkit/network/Network.java
  src/main/java/cn/nukkit/network/protocol/AddPlayerPacket.java
  src/main/java/cn/nukkit/network/protocol/AvailableCommandsPacket.java
  src/main/java/cn/nukkit/network/protocol/DataPacket.java
  src/main/java/cn/nukkit/network/protocol/LoginPacket.java
  src/main/java/cn/nukkit/network/protocol/NetworkStackLatencyPacket.java
  src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
  src/main/java/cn/nukkit/network/protocol/ResourcePackClientResponsePacket.java
  src/main/java/cn/nukkit/network/protocol/ResourcePacksInfoPacket.java
  src/main/java/cn/nukkit/network/protocol/StartGamePacket.java
  src/main/java/cn/nukkit/network/protocol/UpdateSoftEnumPacket.java
  src/main/java/cn/nukkit/raknet/RakNet.java
  src/main/resources/runtimeid_table.json
Labels: [Priority] Urgent, [Status] Needs Testing, [Type] Feature
