Repository CloudburstMC/Nukkit, pull requests merged in 2018-09, with the labels that each got.

#348 fix can't cancel EntityPortalEnterEvent
  src/main/java/cn/nukkit/entity/Entity.java
Labels: [Priority] Low, [Type] Enhancement

#366 Fix hoppers interacting with furnaces
  src/main/java/cn/nukkit/blockentity/BlockEntityHopper.java
Labels: [Priority] Low, [Status] Merged, [Type] Enhancement

#371 Fix magma blocks
  src/main/java/cn/nukkit/block/BlockMagma.java
  src/main/java/cn/nukkit/entity/EntityLiving.java
Labels: [Priority] Low, [Status] Needs Testing, [Type] Enhancement
