Repository CloudburstMC/Nukkit, pull requests merged in 2020-04, with the labels that each got.

#1286 Fix Array Allocation Vulnerability
  src/main/java/cn/nukkit/network/protocol/AvailableCommandsPacket.java
  src/main/java/cn/nukkit/network/protocol/CraftingEventPacket.java
  src/main/java/cn/nukkit/network/protocol/InventoryContentPacket.java
  src/main/java/cn/nukkit/network/protocol/InventoryTransactionPacket.java
  src/main/java/cn/nukkit/network/protocol/TextPacket.java
  src/main/java/cn/nukkit/utils/BinaryStream.java
Labels: [Status] Waiting for Response

#1384 Send only required data when player action is cancelled
  src/main/java/cn/nukkit/entity/data/SyncedEntityData.java
  src/main/java/cn/nukkit/entity/impl/BaseEntity.java
  src/main/java/cn/nukkit/player/handler/PlayerPacketHandler.java
Labels: 2.0, [Status] Merged, [Type] Enhancement

#1379 Forms API
  src/main/java/cn/nukkit/entity/Attribute.java
  src/main/java/cn/nukkit/form/CustomForm.java
  src/main/java/cn/nukkit/form/Form.java
  src/main/java/cn/nukkit/form/ModalForm.java
  src/main/java/cn/nukkit/form/SimpleForm.java
  src/main/java/cn/nukkit/form/element/Element.java
  src/main/java/cn/nukkit/form/element/ElementButton.java
  src/main/java/cn/nukkit/form/element/ElementDropdown.java
  src/main/java/cn/nukkit/form/element/ElementInput.java
  src/main/java/cn/nukkit/form/element/ElementLabel.java
  src/main/java/cn/nukkit/form/element/ElementSlider.java
  src/main/java/cn/nukkit/form/element/ElementStepSlider.java
  src/main/java/cn/nukkit/form/element/ElementToggle.java
  src/main/java/cn/nukkit/form/response/CustomFormResponse.java
  src/main/java/cn/nukkit/form/response/SimpleFormResponse.java
  src/main/java/cn/nukkit/form/util/ImageData.java
  src/main/java/cn/nukkit/player/Player.java
  src/main/java/cn/nukkit/player/handler/PlayerPacketHandler.java
Labels: 2.0
