Repository CloudburstMC/Nukkit, pull requests merged in 2020-01, with the labels that each got.

#1081 Unsafe runtime ID block access
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/event/server/RegistriesClosedEvent.java
  src/main/java/cn/nukkit/level/ChunkManager.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/level/chunk/BlockStorage.java
  src/main/java/cn/nukkit/level/chunk/Chunk.java
  src/main/java/cn/nukkit/level/chunk/ChunkSection.java
  src/main/java/cn/nukkit/level/chunk/IChunk.java
  src/main/java/cn/nukkit/level/chunk/LockableChunk.java
  src/main/java/cn/nukkit/level/chunk/UnsafeChunk.java
  src/main/java/cn/nukkit/level/generator/NormalGenerator.java
  src/main/java/cn/nukkit/level/generator/SimpleChunkManager.java
Labels: [Type] API, [Type] Enhancement

#1089 Campfire
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/block/BlockCampfire.java
  src/main/java/cn/nukkit/blockentity/BlockEntity.java
  src/main/java/cn/nukkit/blockentity/BlockEntityCampfire.java
  src/main/java/cn/nukkit/inventory/CraftingManager.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemCampfire.java
  src/main/java/cn/nukkit/registry/BlockRegistry.java
  src/main/java/cn/nukkit/registry/ItemRegistry.java
Labels: [Status] Waiting for Response, [Type] Feature

#940 Implement offhand
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/entity/EntityHuman.java
  src/main/java/cn/nukkit/entity/EntityHumanType.java
  src/main/java/cn/nukkit/inventory/InventoryType.java
  src/main/java/cn/nukkit/inventory/PlayerOffhandInventory.java
  src/main/java/cn/nukkit/item/ItemBow.java
Labels: [Status] Needs Testing
