Repository CloudburstMC/Nukkit, pull requests merged in 2020-02, with the labels that each got.

#1124 [2.0] Fixes AreaEffectCloud collision rules
  src/main/java/cn/nukkit/entity/impl/misc/EntityAreaEffectCloud.java
Labels: [Status] Conflicts, [Status] Merged

#1132 [2.0] Implements the Barrel block
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/block/BlockBarrel.java
  src/main/java/cn/nukkit/blockentity/BlockEntity.java
  src/main/java/cn/nukkit/blockentity/BlockEntityBarrel.java
  src/main/java/cn/nukkit/inventory/BarrelInventory.java
  src/main/java/cn/nukkit/inventory/InventoryType.java
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: [Status] Conflicts

#1138 [2.0] Implements the Dried Kelp Block
  src/main/java/cn/nukkit/block/BlockDriedKelp.java
  src/main/java/cn/nukkit/inventory/Fuel.java
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: [Status] Conflicts

#1144 [2.0] Adds acacia, birch, dark_oak, jungle and spruce pressure plates
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: [Status] Conflicts

#1092 Redo world config
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/level/EnumLevel.java
  src/main/java/cn/nukkit/level/LevelBuilder.java
  src/main/java/cn/nukkit/level/LevelData.java
  src/main/java/cn/nukkit/level/generator/FlatGenerator.java
  src/main/java/cn/nukkit/level/generator/Generator.java
  src/main/java/cn/nukkit/level/generator/GeneratorFactory.java
  src/main/java/cn/nukkit/level/generator/NetherGenerator.java
  src/main/java/cn/nukkit/level/generator/NormalGenerator.java
Labels: BC Breaking, [Status] Needs Testing

#1165 [2.0] Implements Lectern Block
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/block/BlockLectern.java
  src/main/java/cn/nukkit/blockentity/BlockEntity.java
  src/main/java/cn/nukkit/blockentity/BlockEntityLectern.java
  src/main/java/cn/nukkit/event/block/LecternDropBookEvent.java
  src/main/java/cn/nukkit/event/block/LecternPageChangeEvent.java
  src/main/java/cn/nukkit/event/block/LecternPlaceBookEvent.java
  src/main/java/cn/nukkit/player/Player.java
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: [Status] Conflicts

#1164 [2.0] Waterlogging fixes and improvements
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockAnvil.java
  src/main/java/cn/nukkit/block/BlockBanner.java
  src/main/java/cn/nukkit/block/BlockBarrier.java
  src/main/java/cn/nukkit/block/BlockBeacon.java
  src/main/java/cn/nukkit/block/BlockBed.java
  src/main/java/cn/nukkit/block/BlockBrewingStand.java
  src/main/java/cn/nukkit/block/BlockButton.java
  src/main/java/cn/nukkit/block/BlockCactus.java
  src/main/java/cn/nukkit/block/BlockCake.java
  src/main/java/cn/nukkit/block/BlockCampfire.java
  src/main/java/cn/nukkit/block/BlockCarpet.java
  src/main/java/cn/nukkit/block/BlockChest.java
  src/main/java/cn/nukkit/block/BlockCobweb.java
  src/main/java/cn/nukkit/block/BlockCocoa.java
  src/main/java/cn/nukkit/block/BlockDaylightDetector.java
  src/main/java/cn/nukkit/block/BlockDaylightDetectorInverted.java
  src/main/java/cn/nukkit/block/BlockDeadBush.java
  src/main/java/cn/nukkit/block/BlockDoor.java
  src/main/java/cn/nukkit/block/BlockDragonEgg.java
  src/main/java/cn/nukkit/block/BlockEnchantingTable.java
  src/main/java/cn/nukkit/block/BlockEndPortalFrame.java
  src/main/java/cn/nukkit/block/BlockEndRod.java
  src/main/java/cn/nukkit/block/BlockEnderChest.java
  src/main/java/cn/nukkit/block/BlockFence.java
  src/main/java/cn/nukkit/block/BlockFenceGate.java
  src/main/java/cn/nukkit/block/BlockFlowerPot.java
  src/main/java/cn/nukkit/block/BlockGlassPane.java
  src/main/java/cn/nukkit/block/BlockHopper.java
  src/main/java/cn/nukkit/block/BlockIronBars.java
  src/main/java/cn/nukkit/block/BlockItemFrame.java
  src/main/java/cn/nukkit/block/BlockLadder.java
  src/main/java/cn/nukkit/block/BlockLava.java
  src/main/java/cn/nukkit/block/BlockLeaves.java
  src/main/java/cn/nukkit/block/BlockLever.java
  src/main/java/cn/nukkit/block/BlockLiquid.java
  src/main/java/cn/nukkit/block/BlockMobSpawner.java
  src/main/java/cn/nukkit/block/BlockPistonBase.java
  src/main/java/cn/nukkit/block/BlockPistonHead.java
  src/main/java/cn/nukkit/block/BlockPressurePlateBase.java
  src/main/java/cn/nukkit/block/BlockRedstoneDiode.java
  src/main/java/cn/nukkit/block/BlockSignPost.java
  src/main/java/cn/nukkit/block/BlockSkull.java
  src/main/java/cn/nukkit/block/BlockSlab.java
  src/main/java/cn/nukkit/block/BlockStairs.java
  src/main/java/cn/nukkit/block/BlockTrapdoor.java
  src/main/java/cn/nukkit/block/BlockTripWire.java
  src/main/java/cn/nukkit/block/BlockTripWireHook.java
  src/main/java/cn/nukkit/block/BlockUndyedShulkerBox.java
  src/main/java/cn/nukkit/block/BlockVine.java
  src/main/java/cn/nukkit/block/BlockWall.java
  src/main/java/cn/nukkit/block/BlockWater.java
  src/main/java/cn/nukkit/entity/impl/BaseEntity.java
  src/main/java/cn/nukkit/item/ItemBucket.java
  src/main/java/cn/nukkit/level/BlockPosition.java
  src/main/java/cn/nukkit/level/Level.java
Labels: [Status] Conflicts
